clc;
clear;
t=-2:0.01:2;
y1=sin(2*pi*t);
y2=cos(2*pi*t).*exp(-2*j*t);
subplot(4,2,1);
plot(t,y1);
title("original signal (y1= sin(2pit))");
subplot(4,2,2);
plot(t,y2);
title("original signal (y2= cos(2pit)exp(-2jt))");
subplot(4,2,3);
plot(t,real(y1));
title("real part of (y1= sin(2pit))");
subplot(4,2,4);
plot(t,real(y2));
title("real part of (y2= cos(2pit)exp(-2jt))");
subplot(4,2,5);
plot(t,imag(y1));
title("imaginary part of (y1= sin(2pit))");
subplot(4,2,6);
plot(t,imag(y2));
title("imaginary part of (y2= cos(2pit)exp(-2jt))");